### ISSUE TITLE
crash on 1.16.5

### ISSUE THREAD

**Issue by trilliam25** [Eng1N33R/MechanicalTech#19]
I removed this mod from the list and Minecraft ran.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/12/21 8:57 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at net.minecraft.client.util.Window.redirect$cdn000$onCreateCapabilities(Window:1553)
	at net.minecraft.client.util.Window.<init>(Window:106)
	at net.minecraft.client.util.WindowProvider.createWindow(WindowProvider:21)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:461)
	at net.minecraft.client.main.Main.main(Main:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1364913072.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1364913072.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 717643096 bytes (684 MB) / 2351431680 bytes (2242 MB) up to 6949961728 bytes (6628 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7456m -Xms256m -XX:PermSize=256m
	Suspected Mods: Fabric Loader (fabricloader)
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.7
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		architectury: Architectury 1.8.130
		autoconfig1u: Auto Config v1 Updated 3.3.1
		backslot: BackSlot 1.1.9
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterend: Better End 0.9.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.1.6
		capes: Capes 1.1.1
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cavebiomes: Cave Biomes 0.6.2
		chainmail: Chainmail 0.5.0
		chiseldecor: Chisel Decor 1.1.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.14
		cloth-utils-v1: Cloth Utils v1 1.4.5
		colormatic: Colormatic 2.2.8+mc.1.16.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		computercraft: CC:T for Fabric 1.91.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crawl: Crawl 0.8.2
		croptopia: Croptopia 1.3.0
		crowdin-translate: CrowdinTranslate 1.2
		cullleaves: Cull Leaves 2.1.0
		custom-fog: Custom Fog 1.4.0
		dark-loading-screen: Dark Loading Screen 1.6.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dynamicfps: Dynamic FPS 2.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		dynamo_api: Dynamo API 1.0.0+1.16
		engilib: EngiLib 1.0.0+1.16.4
		expandedstorage: ExpandedStorage 5.6.33
		extraalchemy: Extra Alchemy 1.4.2
		fabric: Fabric API 0.31.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		fabrishot: Fabrishot 1.3.0
		fallingleaves: Falling Leaves 1.5.0+1.16.5
		fallingtree: FallingTree 2.10.2
		fastchest: FastChest 1.2+1.16
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 2.0.0-SNAPSHOT
		healthblast: Health Blast 1.0.0
		hydrogen: Hydrogen 0.2
		imm_ptl_core: Immersive Portals Core 0.80
		immersive_portals: Immersive Portals 0.80
		improved-stations: Improved Stations 2.0.3
		inmis: Inmis 2.1.2-1.16.4
		inventorysorter: Inventory Sorter 1.7.8-1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		jumploader: Jumploader 2.1.3
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.3+1.16.5
		lithium: Lithium 0.6.4
		maelstrom_library: Maelstrom Library 1.0-1.16.5
		mambience: MAmbience 3.0.0+1.16.5
		mechanicaltech: Mechanical Tech 0.3.0+1.16
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.2-1.16.5
		modmenu: Mod Menu 1.16.8
		mostructures: Mo' Structures 1.1.0+mc.1.16.5
		nofade: No Fade 1.16.5-1.0.1
		notenoughanimations: NotEnoughAnimations 1.1.0
		notenoughcrashes: Not Enough Crashes 3.1.8
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		oro_config: OroArmor Config 1.2.0
		phosphor: Phosphor 0.7.1+build.11
		pling: Pling 1.3.0
		raisedclouds: Raised Clouds 1.0.0
		repurposed_structures: Repurposed Structures 1.16.5-1.8.7
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.10.184
		roughlyenoughitems-api: REI (API) 5.10.184
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.184
		roughlyenoughitems-runtime: REI (Runtime) 5.10.184
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		smoothboot: Smooth Boot 1.16.5-1.5.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.1.0
		sodium-extra: Sodium Extra 0.2.2
		spruceui: SpruceUI 2.0.4+1.16
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		timecraft: Craft Takes Time 0.4.4
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		transliterationlib: TRansliterationLib 1.0.2
		traverse: Traverse 3.3.2
		voyager: Voyager 1.0.0
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Launched Version: Jumploader
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7926, Intel
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by EngiN33R** [comment]
Hello! Looks like the crash is caused in some way by the CPW launcher - are you using it to run your Minecraft client? I will try to review what might be causing the crashes, but because the CPW launcher is highly experimental, this issue is a little lower on the priority list. I welcome any pull requests from people more experienced with the CPW launcher.

**Comment by ghost** [comment]
Crashed on my Server too...

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mechanicaltech'!
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6) ~[?:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main:92) [intermediary-minecraft_server.1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at io.engi.mechanicaltech.MechanicalTech.onInitialize(MechanicalTech.java:18) ~[mechtech.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.IllegalArgumentException: Cannot set property class_2746{name=locked, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.State.with(State:114) ~[?:?]
	at io.engi.mechanicaltech.block.SpindleBlock.<init>(SpindleBlock.java:26) ~[mechtech.jar:?]
	at io.engi.mechanicaltech.registry.BlockRegistry.<clinit>(BlockRegistry.java:49) ~[mechtech.jar:?]
	at io.engi.mechanicaltech.MechanicalTech.onInitialize(MechanicalTech.java:18) ~[mechtech.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
```
